// ClientApp/src/Components/Form/FileInput.tsx
import { fileSize } from '@/utils';
import { Omit } from 'lodash';
import React, { ComponentProps, useRef, useState } from 'react';

interface FileInputProps extends Omit<ComponentProps<'input'>, 'onChange'> {
    error?: string;
    onChange?: (file: File | null) => void;
}

export default function FileInput({ name, error, onChange }: FileInputProps) {
    const fileInput = useRef<HTMLInputElement>(null);
    const [file, setFile] = useState<File | null>(null);

    function handleBrowse() {
        fileInput?.current?.click();
    }

    function handleRemove() {
        setFile(null);
        onChange?.(null);

        // fileInput?.current?.value = '';
    }

    function handleChange(e: React.FormEvent<HTMLInputElement>) {
        const files = e.currentTarget?.files as FileList;
        const file = files[0] || null;

        setFile(file);
        onChange?.(file);
    }

    return (
        <div
            className={`form-input w-full rounded border-gray-300 p-0 focus:border-indigo-400 focus:ring-1 focus:ring-indigo-400 focus:outline-none ${
                error &&
                'border-red-400 focus:border-red-400 focus:ring-red-400'
            }`}
        >
            <input
                id={name}
                ref={fileInput}
                type="file"
                className="hidden"
                onChange={handleChange}
            />
            {!file && (
                <div className="p-2">
                    <BrowseButton text="Browse" onClick={handleBrowse} />
                </div>
            )}
            {file && (
                <div className="flex items-center justify-between p-2">
                    <div className="flex-1 pr-1">
                        {file?.name}
                        <span className="ml-1 text-xs text-gray-600">
                            ({fileSize(file?.size)})
                        </span>
                    </div>
                    <BrowseButton text="Remove" onClick={handleRemove} />
                </div>
            )}
        </div>
    );
}

interface BrowseButtonProps extends ComponentProps<'button'> {
    text: string;
}

function BrowseButton({ text, onClick, ...props }: BrowseButtonProps) {
    return (
        <button
            {...props}
            type="button"
            className="rounded-sm bg-gray-600 px-4 py-1 text-xs font-medium text-white hover:bg-gray-700 focus:outline-none"
            onClick={onClick}
        >
            {text}
        </button>
    );
}

// ClientApp/src/Shared/FileInput.vue
<template>
  <div>
    <label v-if="label" class="form-label">{{ label }}:</label>
    <div class="form-input p-0" :class="{ error: errors.length }">
      <input ref="file" type="file" :accept="accept" class="hidden" @change="change" />
      <div v-if="!modelValue" class="p-2">
        <button type="button" class="px-4 py-1 text-white text-xs font-medium bg-gray-500 hover:bg-gray-700 rounded-sm" @click="browse">Browse</button>
      </div>
      <div v-else class="flex items-center justify-between p-2">
        <div class="flex-1 pr-1">
          {{ modelValue.name }} <span class="text-gray-500 text-xs">({{ filesize(modelValue.size) }})</span>
        </div>
        <button type="button" class="px-4 py-1 text-white text-xs font-medium bg-gray-500 hover:bg-gray-700 rounded-sm" @click="remove">Remove</button>
      </div>
    </div>
    <div v-if="errors.length" class="form-error">{{ errors[0] }}</div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

// Define props with types
interface Props {
  modelValue?: File | null
  label?: string
  accept?: string
  errors?: string[]
}

const props = withDefaults(defineProps<Props>(), {
  errors: () => []
})

// Define emits
const emit = defineEmits<{
  'update:modelValue': [value: File | null]
}>()

// Template ref
const file = ref<HTMLInputElement>()

// Watch modelValue to clear input when null
watch(() => props.modelValue, (value) => {
  if (!value && file.value) {
    file.value.value = ''
  }
})

// Methods
const filesize = (size: number): string => {
  const i = Math.floor(Math.log(size) / Math.log(1024))
  return (size / Math.pow(1024, i)).toFixed(2) as any * 1 + ' ' + ['B', 'kB', 'MB', 'GB', 'TB'][i]
}

const browse = () => {
  file.value?.click()
}

const change = (e: Event) => {
  const target = e.target as HTMLInputElement
  const selectedFile = target.files?.[0] || null
  emit('update:modelValue', selectedFile)
}

const remove = () => {
  emit('update:modelValue', null)
}
</script>
