// ClientApp/src/Shared/Pagination.vue
<template>
  <div v-if="links && links.length > 3">
    <div class="flex flex-wrap -mb-1">
      <template v-for="(link, key) in links">
        <div v-if="link.url === null" :key="key" class="mb-1 mr-1 px-4 py-3 text-gray-400 text-sm leading-4 border rounded" v-html="link.label" />
        <Link v-else :key="`link-${key}`" class="mb-1 mr-1 px-4 py-3 focus:text-indigo-500 text-sm leading-4 hover:bg-white border focus:border-indigo-500 rounded" :class="{ 'bg-white': link.active }" :href="link.url" v-html="link.label" />
      </template>
    </div>
  </div>
</template>

<script>
import { Link } from '@inertiajs/vue3'

export default {
  components: {
    Link,
  },
  props: {
    links: Array,
  },
}
</script>

// ClientApp/src/Components/Pagination/Pagination.tsx
import { Link } from '@inertiajs/react';
import classNames from 'classnames';

interface PaginationProps {
    links: PaginationItem[];
}

export default function Pagination({ links = [] }: PaginationProps) {
    /**
     * If there are only 3 links, it means there are no previous or next pages.
     * So, we don't need to render the pagination.
     */
    if (links.length === 3) return null;

    return (
        <div className="mt-6 -mb-1 flex flex-wrap">
            {links?.map((link) => {
                return link?.url === null ? (
                    <PageInactive key={link.label} label={link.label} />
                ) : (
                    <PaginationItem key={link.label} {...link} />
                );
            })}
        </div>
    );
}

interface PaginationItem {
    url: null | string;
    label: string;
    active: boolean;
}

function PaginationItem({ active, label, url }: PaginationItem) {
    const className = classNames(
        [
            'mr-1 mb-1',
            'px-4 py-3',
            'border border-solid border-gray-300 rounded',
            'text-sm',
            'hover:bg-white',
            'focus:outline-none focus:border-indigo-700 focus:text-indigo-700',
        ],
        {
            'bg-white': active,
        },
    );

    /**
     * Note: In general you should be aware when using `dangerouslySetInnerHTML`.
     *
     * In this case, `label` from the API is a string, so it's safe to use it.
     * It will be either `&laquo; Previous` or `Next &raquo;`
     */
    return (
        <Link className={className} href={url as string}>
            <span dangerouslySetInnerHTML={{ __html: label }}></span>
        </Link>
    );
}

function PageInactive({ label }: Pick<PaginationItem, 'label'>) {
    const className = classNames(
        'mr-1 mb-1 px-4 py-3 text-sm border rounded border-solid border-gray-300 text-gray',
    );

    /**
     * Note: In general you should be aware when using `dangerouslySetInnerHTML`.
     *
     * In this case, `label` from the API is a string, so it's safe to use it.
     * It will be either `&laquo; Previous` or `Next &raquo;`
     */
    return (
        <div
            className={className}
            dangerouslySetInnerHTML={{ __html: label }}
        />
    );
}
