// ClientApp/src/Pages/Contacts/Create.tsx
import LoadingButton from '@/Components/Button/LoadingButton';
import FieldGroup from '@/Components/Form/FieldGroup';
import SelectInput from '@/Components/Form/SelectInput';
import TextInput from '@/Components/Form/TextInput';
import MainLayout from '@/Layouts/MainLayout';
import { Organization } from '@/types';
import { Link, useForm, usePage } from '@inertiajs/react';

const Create = () => {
    const { organizations } = usePage<{ organizations: Organization[] }>()
        .props;
    const { data, setData, errors, post, processing } = useForm({
        first_name: '',
        last_name: '',
        organization_id: '',
        email: '',
        phone: '',
        address: '',
        city: '',
        region: '',
        country: '',
        postal_code: '',
    });

    function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        post('/contacts');
    }

    return (
        <div>
            <h1 className="mb-8 text-3xl font-bold">
                <Link
                    href="/contacts"
                    className="text-indigo-600 hover:text-indigo-700"
                >
                    Contacts
                </Link>
                <span className="font-medium text-indigo-600"> /</span> Create
            </h1>
            <div className="max-w-3xl overflow-hidden rounded bg-white shadow">
                <form onSubmit={handleSubmit}>
                    <div className="grid gap-8 p-8 lg:grid-cols-2">
                        <FieldGroup
                            label="First Name"
                            name="first_name"
                            error={errors.first_name}
                        >
                            <TextInput
                                name="first_name"
                                error={errors.first_name}
                                value={data.first_name}
                                onChange={(e) =>
                                    setData('first_name', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Last Name"
                            name="last_name"
                            error={errors.last_name}
                        >
                            <TextInput
                                name="last_name"
                                error={errors.last_name}
                                value={data.last_name}
                                onChange={(e) =>
                                    setData('last_name', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Organization"
                            name="organization_id"
                            error={errors?.organization_id}
                        >
                            <SelectInput
                                name="organization_id"
                                error={errors.organization_id}
                                value={data.organization_id}
                                onChange={(e) =>
                                    setData('organization_id', e.target.value)
                                }
                                options={organizations?.map(({ id, name }) => ({
                                    value: String(id),
                                    label: name,
                                }))}
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Email"
                            name="email"
                            error={errors.email}
                        >
                            <TextInput
                                name="email"
                                type="email"
                                error={errors.email}
                                value={data.email}
                                onChange={(e) =>
                                    setData('email', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Phone"
                            name="phone"
                            error={errors.phone}
                        >
                            <TextInput
                                name="phone"
                                error={errors.phone}
                                value={data.phone}
                                onChange={(e) =>
                                    setData('phone', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Address"
                            name="address"
                            error={errors.address}
                        >
                            <TextInput
                                name="address"
                                error={errors.address}
                                value={data.address}
                                onChange={(e) =>
                                    setData('address', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="City"
                            name="city"
                            error={errors.city}
                        >
                            <TextInput
                                name="city"
                                error={errors.city}
                                value={data.city}
                                onChange={(e) =>
                                    setData('city', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Region"
                            name="region"
                            error={errors.region}
                        >
                            <TextInput
                                name="region"
                                error={errors.region}
                                value={data.region}
                                onChange={(e) =>
                                    setData('region', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Country"
                            name="country"
                            error={errors.country}
                        >
                            <SelectInput
                                name="country"
                                error={errors.country}
                                value={data.country}
                                onChange={(e) =>
                                    setData('country', e.target.value)
                                }
                                options={[
                                    { value: 'CA', label: 'Canada' },
                                    { value: 'US', label: 'United States' },
                                ]}
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Postal Code"
                            name="postal_code"
                            error={errors.postal_code}
                        >
                            <TextInput
                                name="postal_code"
                                error={errors.postal_code}
                                value={data.postal_code}
                                onChange={(e) =>
                                    setData('postal_code', e.target.value)
                                }
                            />
                        </FieldGroup>
                    </div>
                    <div className="flex items-center justify-end border-t border-gray-200 bg-gray-100 px-8 py-4">
                        <LoadingButton
                            loading={processing}
                            type="submit"
                            className="btn-indigo"
                        >
                            Create Contact
                        </LoadingButton>
                    </div>
                </form>
            </div>
        </div>
    );
};

/**
 * Persistent Layout (Inertia.js)
 *
 * [Learn more](https://inertiajs.com/pages#persistent-layouts)
 */
Create.layout = (page: React.ReactNode) => (
    <MainLayout title="Create Contact" children={page} />
);

export default Create;

// ClientApp/src/Pages/Contacts/Create.vue
<template>
    <div>
        <Head title="Create Contact" />
        <h1 class="mb-8 text-3xl font-bold">
            <Link class="text-indigo-400 hover:text-indigo-600" href="/contacts"
                >Contacts</Link
            >
            <span class="font-medium text-indigo-400">/</span> Create
        </h1>
        <div class="max-w-3xl overflow-hidden rounded-md bg-white shadow">
            <form @submit.prevent="store">
                <div class="-mb-8 -mr-6 flex flex-wrap p-8">
                    <text-input
                        v-model="form.first_name"
                        :error="form.errors.first_name"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="First name"
                    />
                    <text-input
                        v-model="form.last_name"
                        :error="form.errors.last_name"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Last name"
                    />
                    <select-input
                        v-model="form.organization_id"
                        :error="form.errors.organization_id"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Organization"
                    >
                        <option :value="null" />
                        <option
                            v-for="organization in organizations"
                            :key="organization.id"
                            :value="organization.id"
                        >
                            {{ organization.name }}
                        </option>
                    </select-input>
                    <text-input
                        v-model="form.email"
                        :error="form.errors.email"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Email"
                    />
                    <text-input
                        v-model="form.phone"
                        :error="form.errors.phone"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Phone"
                    />
                    <text-input
                        v-model="form.address"
                        :error="form.errors.address"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Address"
                    />
                    <text-input
                        v-model="form.city"
                        :error="form.errors.city"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="City"
                    />
                    <text-input
                        v-model="form.region"
                        :error="form.errors.region"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Province/State"
                    />
                    <select-input
                        v-model="form.country"
                        :error="form.errors.country"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Country"
                    >
                        <option :value="null" />
                        <option value="CA">Canada</option>
                        <option value="US">United States</option>
                    </select-input>
                    <text-input
                        v-model="form.postal_code"
                        :error="form.errors.postal_code"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Postal code"
                    />
                </div>
                <div
                    class="flex items-center justify-end border-t border-gray-100 bg-gray-50 px-8 py-4"
                >
                    <loading-button
                        :loading="form.processing"
                        class="btn-indigo"
                        type="submit"
                        >Create Contact</loading-button
                    >
                </div>
            </form>
        </div>
    </div>
</template>

<script setup lang="ts">
import Layout from '@/Shared/Layout.vue';
import LoadingButton from '@/Shared/LoadingButton.vue';
import SelectInput from '@/Shared/SelectInput.vue';
import TextInput from '@/Shared/TextInput.vue';
import type {
    AuthDto,
    ContactViewModel,
    FlashDto,
    Organization,
} from '@/Types/generated';
import { Head, Link, useForm } from '@inertiajs/vue3';

// Define page props
interface Props {
    auth: AuthDto;
    flash: FlashDto;
    organizations: Organization[];
}

defineProps<Props>();

const form = useForm<ContactViewModel>({
    first_name: '',
    last_name: '',
    organization_id: 0,
    email: '',
    phone: '',
    address: '',
    city: '',
    region: '',
    country: '',
    postal_code: '',
});

// Submit function
const store = () => {
    form.post('/contacts');
};

// This component uses Layout as the default layout
defineOptions({
    layout: Layout,
});
</script>
