// ClientApp/src/Pages/Contacts/Index.tsx
import FilterBar from '@/Components/FilterBar/FilterBar';
import Pagination from '@/Components/Pagination/Pagination';
import Table from '@/Components/Table/Table';
import MainLayout from '@/Layouts/MainLayout';
import { Contact, PaginatedData } from '@/types';
import { Link, usePage } from '@inertiajs/react';
import { Trash2 } from 'lucide-react';

const Index = () => {
    const { contacts } = usePage<{
        contacts: PaginatedData<Contact>;
    }>().props;

    const {
        data,
        meta: { links },
    } = contacts;

    return (
        <div>
            <h1 className="mb-8 text-3xl font-bold">Contacts</h1>
            <div className="mb-6 flex items-center justify-between">
                <FilterBar />
                <Link
                    className="btn-indigo focus:outline-none"
                    href="/contacts/create"
                >
                    <span>Create</span>
                    <span className="hidden md:inline"> Contact</span>
                </Link>
            </div>
            <Table
                columns={[
                    {
                        label: 'Name',
                        name: 'name',
                        renderCell: (row) => (
                            <>
                                {row.name}
                                {row.deleted_at && (
                                    <Trash2
                                        size={16}
                                        className="ml-2 text-gray-400"
                                    />
                                )}
                            </>
                        ),
                    },
                    { label: 'Organization', name: 'organization.name' },
                    { label: 'City', name: 'city' },
                    { label: 'Phone', name: 'phone', colSpan: 2 },
                ]}
                rows={data}
                getRowDetailsUrl={(row) => `/contacts/${row.id}/edit`}
            />
            <Pagination links={links} />
        </div>
    );
};

/**
 * Persistent Layout (Inertia.js)
 *
 * [Learn more](https://inertiajs.com/pages#persistent-layouts)
 */
Index.layout = (page: React.ReactNode) => (
    <MainLayout title="Contacts" children={page} />
);

export default Index;

// ClientApp/src/Pages/Contacts/Index.vue
<template>
  <div>
    <Head title="Contacts" />
    <h1 class="mb-8 text-3xl font-bold">Contacts</h1>
    <div class="flex items-center justify-between mb-6">
      <search-filter v-model="form.search" class="mr-4 w-full max-w-md" @reset="reset">
        <label class="block text-gray-700">Trashed:</label>
        <select v-model="form.trashed" class="form-select mt-1 w-full">
          <option :value="null" />
          <option value="with">With Trashed</option>
          <option value="only">Only Trashed</option>
        </select>
      </search-filter>
      <Link class="btn-indigo" href="/contacts/create">
        <span>Create</span>
        <span class="hidden md:inline">&nbsp;Contact</span>
      </Link>
    </div>
    <div class="bg-white rounded-md shadow overflow-x-auto">
      <table class="w-full whitespace-nowrap">
        <tr class="text-left font-bold">
          <th class="pb-4 pt-6 px-6">Name</th>
          <th class="pb-4 pt-6 px-6">Organization</th>
          <th class="pb-4 pt-6 px-6">City</th>
          <th class="pb-4 pt-6 px-6" colspan="2">Phone</th>
        </tr>
        <tr v-for="contact in contacts.data" :key="contact.id" class="hover:bg-gray-100 focus-within:bg-gray-100">
          <td class="border-t">
            <Link class="flex items-center px-6 py-4 focus:text-indigo-500" :href="`/contacts/${contact.id}/edit`">
              {{ contact.name }}
              <icon v-if="contact.deleted_at" name="trash" class="shrink-0 ml-2 w-3 h-3 fill-gray-400" />
            </Link>
          </td>
          <td class="border-t">
            <Link class="flex items-center px-6 py-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
              <div v-if="contact.organization">
                {{ contact.organization.name }}
              </div>
            </Link>
          </td>
          <td class="border-t">
            <Link class="flex items-center px-6 py-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
              {{ contact.city }}
            </Link>
          </td>
          <td class="border-t">
            <Link class="flex items-center px-6 py-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
              {{ contact.phone }}
            </Link>
          </td>
          <td class="w-px border-t">
            <Link class="flex items-center px-4" :href="`/contacts/${contact.id}/edit`" tabindex="-1">
              <icon name="cheveron-right" class="block w-6 h-6 fill-gray-400" />
            </Link>
          </td>
        </tr>
        <tr v-if="contacts.data.length === 0">
          <td class="px-6 py-4 border-t" colspan="4">No contacts found.</td>
        </tr>
      </table>
    </div>
    <pagination class="mt-6" :links="contacts.links" />
  </div>
</template>

<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'
import { reactive, watch } from 'vue'
import { router } from '@inertiajs/vue3'
import Icon from '@/Shared/Icon.vue'
import pickBy from 'lodash/pickBy'
import Layout from '@/Shared/Layout.vue'
import throttle from 'lodash/throttle'
import mapValues from 'lodash/mapValues'
import Pagination from '@/Shared/Pagination.vue'
import SearchFilter from '@/Shared/SearchFilter.vue'
import type { Contact, AuthDto, FlashDto, PaginatedData, SearchFilters } from '@/Types/generated'

// Define page props
interface Props {
  auth: AuthDto
  flash: FlashDto
  filters: SearchFilters
  contacts: PaginatedData<Contact>
}

const props = defineProps<Props>()

// Reactive form state
const form = reactive<SearchFilters>({
  search: props.filters.search,
  trashed: props.filters.trashed,
})

// Watch form changes with throttling
watch(
  form,
  throttle(() => {
    router.get('/contacts', pickBy(form), { preserveState: true })
  }, 150),
  { deep: true }
)

// Reset form function
const reset = () => {
  Object.assign(form, mapValues(form, () => null))
}

// This component uses Layout as the default layout
defineOptions({
  layout: Layout,
})
</script>
