// ClientApp/src/Pages/Contacts/Edit.vue
<template>
  <div>
    <Head :title="`${form.first_name} ${form.last_name}`" />
    <h1 class="mb-8 text-3xl font-bold">
      <Link class="text-indigo-400 hover:text-indigo-600" href="/contacts">Contacts</Link>
      <span class="text-indigo-400 font-medium">/</span>
      {{ form.first_name }} {{ form.last_name }}
    </h1>
    <trashed-message v-if="contact.deleted_at" class="mb-6" @restore="restore"> This contact has been deleted. </trashed-message>
    <div class="max-w-3xl bg-white rounded-md shadow overflow-hidden">
      <form @submit.prevent="update">
        <div class="flex flex-wrap -mb-8 -mr-6 p-8">
          <text-input v-model="form.first_name" :error="form.errors.first_name" class="pb-8 pr-6 w-full lg:w-1/2" label="First name" />
          <text-input v-model="form.last_name" :error="form.errors.last_name" class="pb-8 pr-6 w-full lg:w-1/2" label="Last name" />
          <select-input v-model="form.organization_id" :error="form.errors.organization_id" class="pb-8 pr-6 w-full lg:w-1/2" label="Organization">
            <option :value="null" />
            <option v-for="organization in organizations" :key="organization.id" :value="organization.id">{{ organization.name }}</option>
          </select-input>
          <text-input v-model="form.email" :error="form.errors.email" class="pb-8 pr-6 w-full lg:w-1/2" label="Email" />
          <text-input v-model="form.phone" :error="form.errors.phone" class="pb-8 pr-6 w-full lg:w-1/2" label="Phone" />
          <text-input v-model="form.address" :error="form.errors.address" class="pb-8 pr-6 w-full lg:w-1/2" label="Address" />
          <text-input v-model="form.city" :error="form.errors.city" class="pb-8 pr-6 w-full lg:w-1/2" label="City" />
          <text-input v-model="form.region" :error="form.errors.region" class="pb-8 pr-6 w-full lg:w-1/2" label="Province/State" />
          <select-input v-model="form.country" :error="form.errors.country" class="pb-8 pr-6 w-full lg:w-1/2" label="Country">
            <option :value="null" />
            <option value="CA">Canada</option>
            <option value="US">United States</option>
          </select-input>
          <text-input v-model="form.postal_code" :error="form.errors.postal_code" class="pb-8 pr-6 w-full lg:w-1/2" label="Postal code" />
        </div>
        <div class="flex items-center px-8 py-4 bg-gray-50 border-t border-gray-100">
          <button v-if="!contact.deleted_at" class="text-red-600 hover:underline" tabindex="-1" type="button" @click="destroy">Delete Contact</button>
          <loading-button :loading="form.processing" class="btn-indigo ml-auto" type="submit">Update Contact</loading-button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'
import { useForm, router } from '@inertiajs/vue3'
import Layout from '@/Shared/Layout.vue'
import TextInput from '@/Shared/TextInput.vue'
import SelectInput from '@/Shared/SelectInput.vue'
import LoadingButton from '@/Shared/LoadingButton.vue'
import TrashedMessage from '@/Shared/TrashedMessage.vue'
import type { Contact, Organization, AuthDto, FlashDto, ContactViewModel } from '@/Types/generated'

// Define page props
interface Props {
  auth: AuthDto
  flash: FlashDto
  contact: Contact
  organizations: Organization[]
}

const props = defineProps<Props>()

const form = useForm<ContactViewModel>({
  first_name: props.contact.first_name,
  last_name: props.contact.last_name,
  organization_id: props.contact.organization_id,
  email: props.contact.email,
  phone: props.contact.phone,
  address: props.contact.address,
  city: props.contact.city,
  region: props.contact.region,
  country: props.contact.country,
  postal_code: props.contact.postal_code,
})

// Methods
const update = () => {
  form.put(`/contacts/${props.contact.id}`)
}

const destroy = () => {
  if (confirm('Are you sure you want to delete this contact?')) {
    router.delete(`/contacts/${props.contact.id}`)
  }
}

const restore = () => {
  if (confirm('Are you sure you want to restore this contact?')) {
    router.put(`/contacts/${props.contact.id}/restore`)
  }
}

// This component uses Layout as the default layout
defineOptions({
  layout: Layout,
})
</script>

// ClientApp/src/Pages/Organizations/Edit.tsx
import DeleteButton from '@/Components/Button/DeleteButton';
import LoadingButton from '@/Components/Button/LoadingButton';
import FieldGroup from '@/Components/Form/FieldGroup';
import SelectInput from '@/Components/Form/SelectInput';
import TextInput from '@/Components/Form/TextInput';
import TrashedMessage from '@/Components/Messages/TrashedMessage';
import Table from '@/Components/Table/Table';
import MainLayout from '@/Layouts/MainLayout';
import { Organization } from '@/types';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import React from 'react';

const Edit = () => {
    const { organization } = usePage<{ organization: Organization }>().props;
    const { data, setData, errors, put, processing } = useForm({
        name: organization.name || '',
        email: organization.email || '',
        phone: organization.phone || '',
        address: organization.address || '',
        city: organization.city || '',
        region: organization.region || '',
        country: organization.country || '',
        postal_code: organization.postal_code || '',
    });

    function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        put(`/organizations/${organization.id}`);
    }

    function destroy() {
        if (confirm('Are you sure you want to delete this organization?')) {
            router.delete(`/organizations/${organization.id}`);
        }
    }

    function restore() {
        if (confirm('Are you sure you want to restore this organization?')) {
            router.put(`/organizations/${organization.id}/restore`);
        }
    }

    return (
        <div>
            <Head title={data.name} />
            <h1 className="mb-8 text-3xl font-bold">
                <Link
                    href="/organizations"
                    className="text-indigo-600 hover:text-indigo-700"
                >
                    Organizations
                </Link>
                <span className="mx-2 font-medium text-indigo-600">/</span>
                {data.name}
            </h1>
            {organization.deleted_at && (
                <TrashedMessage
                    message="This organization has been deleted."
                    onRestore={restore}
                />
            )}
            <div className="max-w-3xl overflow-hidden rounded bg-white shadow">
                <form onSubmit={handleSubmit}>
                    <div className="grid gap-8 p-8 lg:grid-cols-2">
                        <FieldGroup
                            label="Name"
                            name="name"
                            error={errors.name}
                        >
                            <TextInput
                                name="name"
                                error={errors.name}
                                value={data.name}
                                onChange={(e) =>
                                    setData('name', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Email"
                            name="email"
                            error={errors.email}
                        >
                            <TextInput
                                name="email"
                                type="email"
                                error={errors.email}
                                value={data.email}
                                onChange={(e) =>
                                    setData('email', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Phone"
                            name="phone"
                            error={errors.phone}
                        >
                            <TextInput
                                name="phone"
                                error={errors.phone}
                                value={data.phone}
                                onChange={(e) =>
                                    setData('phone', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Address"
                            name="address"
                            error={errors.address}
                        >
                            <TextInput
                                name="address"
                                error={errors.address}
                                value={data.address}
                                onChange={(e) =>
                                    setData('address', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="City"
                            name="city"
                            error={errors.city}
                        >
                            <TextInput
                                name="city"
                                error={errors.city}
                                value={data.city}
                                onChange={(e) =>
                                    setData('city', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Province/State"
                            name="region"
                            error={errors.region}
                        >
                            <TextInput
                                name="region"
                                error={errors.region}
                                value={data.region}
                                onChange={(e) =>
                                    setData('region', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Country"
                            name="country"
                            error={errors.country}
                        >
                            <SelectInput
                                name="country"
                                error={errors.country}
                                value={data.country}
                                onChange={(e) =>
                                    setData('country', e.target.value)
                                }
                                options={[
                                    {
                                        value: '',
                                        label: '',
                                    },
                                    {
                                        value: 'CA',
                                        label: 'Canada',
                                    },
                                    {
                                        value: 'US',
                                        label: 'United States',
                                    },
                                ]}
                            />{' '}
                        </FieldGroup>

                        <FieldGroup
                            label="Postal Code"
                            name="postal_code"
                            error={errors.postal_code}
                        >
                            <TextInput
                                name="postal_code"
                                error={errors.postal_code}
                                value={data.postal_code}
                                onChange={(e) =>
                                    setData('postal_code', e.target.value)
                                }
                            />
                        </FieldGroup>
                    </div>
                    <div className="flex items-center border-t border-gray-200 bg-gray-100 px-8 py-4">
                        {!organization.deleted_at && (
                            <DeleteButton onDelete={destroy}>
                                Delete Organization
                            </DeleteButton>
                        )}
                        <LoadingButton
                            loading={processing}
                            type="submit"
                            className="btn-indigo ml-auto"
                        >
                            Update Organization
                        </LoadingButton>
                    </div>
                </form>
            </div>
            <h2 className="mt-12 mb-6 text-2xl font-bold">Contacts</h2>
            <Table
                columns={[
                    { label: 'Name', name: 'name' },
                    { label: 'City', name: 'city' },
                    { label: 'Phone', name: 'phone', colSpan: 2 },
                ]}
                rows={organization.contacts}
                getRowDetailsUrl={(row) => `/contacts/${row.id}/edit`}
            />
        </div>
    );
};

/**
 * Persistent Layout (Inertia.js)
 *
 * [Learn more](https://inertiajs.com/pages#persistent-layouts)
 */
Edit.layout = (page: React.ReactNode) => <MainLayout children={page} />;

export default Edit;
