// ClientApp/src/Pages/Auth/Login.vue
<template>
  <PageHead title="Login" />
  <GuestLayout>
    <form class="bg-white rounded-xl shadow-2xl overflow-hidden backdrop-blur-sm border border-white/20" @submit.prevent="login">
      <div class="px-10 py-12">
        <h1 class="text-center text-3xl font-bold text-gray-800">Welcome Back!</h1>
        <div class="mt-6 mx-auto w-24 border-b-2 border-indigo-500" />
        <text-input v-model="form.email" :error="form.errors.email" class="mt-10" label="Email" type="email" autofocus autocapitalize="off" />
        <text-input v-model="form.password" :error="form.errors.password" class="mt-6" label="Password" type="password" />
        <label class="flex items-center mt-6 select-none" for="remember">
          <input id="remember" v-model="form.remember" class="mr-1" type="checkbox" />
          <span class="text-sm text-gray-600">Remember Me</span>
        </label>
      </div>
      <div class="flex px-10 py-4 bg-gradient-to-r from-gray-50 to-gray-100 border-t border-gray-200">
        <loading-button :loading="form.processing" class="btn-indigo ml-auto" type="submit">Sign In</loading-button>
      </div>
    </form>
  </GuestLayout>
</template>

<script lang="ts">
import { Head } from '@inertiajs/vue3'
import GuestLayout from '@/Shared/GuestLayout.vue'
import TextInput from '@/Shared/TextInput.vue'
import LoadingButton from '@/Shared/LoadingButton.vue'

export default {
  components: {
    PageHead: Head,
    GuestLayout,
    LoadingButton,
    TextInput,
  },
  data() {
    return {
      form: this.$inertia.form({
        email: 'johndoe@example.com',
        password: 'secret',
        remember: false,
      }),
    }
  },
  methods: {
    login() {
      this.form.post('/login')
    },
  },
}
</script>

// ClientApp/src/Pages/Auth/Login.tsx
import LoadingButton from '@/Components/Button/LoadingButton';
import { CheckboxInput } from '@/Components/Form/CheckboxInput';
import FieldGroup from '@/Components/Form/FieldGroup';
import TextInput from '@/Components/Form/TextInput';
import Logo from '@/Components/Logo/Logo';
import { Head, useForm } from '@inertiajs/react';
import React from 'react';

export default function LoginPage() {
    const { data, setData, errors, post, processing } = useForm({
        email: 'johndoe@example.com',
        password: 'secret',
        remember: true,
    });

    function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();

        post('/login');
    }

    return (
        <div className="flex min-h-screen items-center justify-center bg-indigo-900 p-6">
            <Head title="Login" />

            <div className="w-full max-w-md">
                <Logo
                    className="mx-auto block w-full max-w-xs fill-current text-white"
                    height={50}
                />
                <form
                    onSubmit={handleSubmit}
                    className="mt-8 overflow-hidden rounded-lg bg-white shadow-xl"
                >
                    <div className="px-10 py-12">
                        <h1 className="text-center text-3xl font-bold">
                            Welcome Back!
                        </h1>
                        <div className="mx-auto mt-6 w-24 border-b-2" />
                        <div className="grid gap-6">
                            <FieldGroup
                                label="Email"
                                name="email"
                                error={errors.email}
                            >
                                <TextInput
                                    name="email"
                                    type="email"
                                    error={errors.email}
                                    value={data.email}
                                    onChange={(e) =>
                                        setData('email', e.target.value)
                                    }
                                />
                            </FieldGroup>

                            <FieldGroup
                                label="Password"
                                name="password"
                                error={errors.password}
                            >
                                <TextInput
                                    type="password"
                                    error={errors.password}
                                    value={data.password}
                                    onChange={(e) =>
                                        setData('password', e.target.value)
                                    }
                                />
                            </FieldGroup>

                            <FieldGroup>
                                <CheckboxInput
                                    label="Remember Me"
                                    name="remember"
                                    id="remember"
                                    checked={data.remember}
                                    onChange={(e) =>
                                        setData('remember', e.target.checked)
                                    }
                                />
                            </FieldGroup>
                        </div>
                    </div>
                    <div className="flex items-center justify-between border-t border-gray-200 bg-gray-100 px-10 py-4">
                        <a
                            className="hover:underline"
                            tabIndex={-1}
                            href="#reset-password"
                        >
                            Forgot password?
                        </a>
                        <LoadingButton
                            type="submit"
                            loading={processing}
                            className="btn-indigo"
                        >
                            Login
                        </LoadingButton>
                    </div>
                </form>
            </div>
        </div>
    );
}
