// ClientApp/src/Pages/Users/Create.tsx
import LoadingButton from '@/Components/Button/LoadingButton';
import FieldGroup from '@/Components/Form/FieldGroup';
import FileInput from '@/Components/Form/FileInput';
import SelectInput from '@/Components/Form/SelectInput';
import TextInput from '@/Components/Form/TextInput';
import MainLayout from '@/Layouts/MainLayout';
import { Link, useForm } from '@inertiajs/react';

const Create = () => {
    const { data, setData, errors, post, processing } = useForm({
        first_name: '',
        last_name: '',
        email: '',
        password: '',
        owner: '0',
        photo: '',
    });

    function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        post('/users');
    }

    return (
        <div>
            <div>
                <h1 className="mb-8 text-3xl font-bold">
                    <Link
                        href="/users"
                        className="text-indigo-600 hover:text-indigo-700"
                    >
                        Users
                    </Link>
                    <span className="font-medium text-indigo-600"> /</span>{' '}
                    Create
                </h1>
            </div>
            <div className="max-w-3xl overflow-hidden rounded bg-white shadow">
                <form onSubmit={handleSubmit}>
                    <div className="grid gap-8 p-8 lg:grid-cols-2">
                        <FieldGroup
                            label="First Name"
                            name="first_name"
                            error={errors.first_name}
                        >
                            <TextInput
                                name="first_name"
                                error={errors.first_name}
                                value={data.first_name}
                                onChange={(e) =>
                                    setData('first_name', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Last Name"
                            name="last_name"
                            error={errors.last_name}
                        >
                            <TextInput
                                name="last_name"
                                error={errors.last_name}
                                value={data.last_name}
                                onChange={(e) =>
                                    setData('last_name', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Email"
                            name="email"
                            error={errors.email}
                        >
                            <TextInput
                                name="email"
                                type="email"
                                error={errors.email}
                                value={data.email}
                                onChange={(e) =>
                                    setData('email', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Password"
                            name="password"
                            error={errors.password}
                        >
                            <TextInput
                                name="password"
                                type="password"
                                error={errors.password}
                                value={data.password}
                                onChange={(e) =>
                                    setData('password', e.target.value)
                                }
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Owner"
                            name="owner"
                            error={errors.owner}
                        >
                            <SelectInput
                                name="owner"
                                error={errors.owner}
                                value={data.owner}
                                onChange={(e) =>
                                    setData('owner', e.target.value)
                                }
                                options={[
                                    { value: '1', label: 'Yes' },
                                    { value: '0', label: 'No' },
                                ]}
                            />
                        </FieldGroup>

                        <FieldGroup
                            label="Photo"
                            name="photo"
                            error={errors.photo}
                        >
                            <FileInput
                                name="photo"
                                accept="image/*"
                                error={errors.photo}
                                value={data.photo}
                                onChange={(photo) =>
                                    setData('photo', photo as unknown as string)
                                }
                            />
                        </FieldGroup>
                    </div>
                    <div className="flex items-center justify-end border-t border-gray-200 bg-gray-100 px-8 py-4">
                        <LoadingButton
                            loading={processing}
                            type="submit"
                            className="btn-indigo"
                        >
                            Create User
                        </LoadingButton>
                    </div>
                </form>
            </div>
        </div>
    );
};

/**
 * Persistent Layout (Inertia.js)
 *
 * [Learn more](https://inertiajs.com/pages#persistent-layouts)
 */
Create.layout = (page: React.ReactNode) => (
    <MainLayout title="Create User" children={page} />
);

export default Create;

// ClientApp/src/Pages/Users/Create.vue
<template>
    <div>
        <Head title="Create User" />
        <h1 class="mb-8 text-3xl font-bold">
            <Link class="text-indigo-400 hover:text-indigo-600" href="/users"
                >Users</Link
            >
            <span class="font-medium text-indigo-400">/</span> Create
        </h1>
        <div class="max-w-3xl overflow-hidden rounded-md bg-white shadow">
            <form @submit.prevent="store">
                <div class="-mb-8 -mr-6 flex flex-wrap p-8">
                    <text-input
                        v-model="form.first_name"
                        :error="form.errors.first_name"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="First name"
                    />
                    <text-input
                        v-model="form.last_name"
                        :error="form.errors.last_name"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Last name"
                    />
                    <text-input
                        v-model="form.email"
                        :error="form.errors.email"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Email"
                    />
                    <text-input
                        v-model="form.password"
                        :error="form.errors.password"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        type="password"
                        autocomplete="new-password"
                        label="Password"
                    />
                    <select-input
                        v-model="form.owner"
                        :error="form.errors.owner"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        label="Owner"
                    >
                        <option :value="true">Yes</option>
                        <option :value="false">No</option>
                    </select-input>
                    <file-input
                        v-model="form.photo"
                        :error="form.errors.photo"
                        class="w-full pb-8 pr-6 lg:w-1/2"
                        type="file"
                        accept="image/*"
                        label="Photo"
                    />
                </div>
                <div
                    class="flex items-center justify-end border-t border-gray-100 bg-gray-50 px-8 py-4"
                >
                    <loading-button
                        :loading="form.processing"
                        class="btn-indigo"
                        type="submit"
                        >Create User</loading-button
                    >
                </div>
            </form>
        </div>
    </div>
</template>

<script setup lang="ts">
import FileInput from '@/Shared/FileInput.vue';
import Layout from '@/Shared/Layout.vue';
import LoadingButton from '@/Shared/LoadingButton.vue';
import SelectInput from '@/Shared/SelectInput.vue';
import TextInput from '@/Shared/TextInput.vue';
import type { CreateUserForm, InertiaSharedProps } from '@/Types/generated';
import { Head, Link, useForm } from '@inertiajs/vue3';

// Define page props
type Props = InertiaSharedProps<{
    [key: string]: unknown;
}>;

// Important: hand defineProps a **resolved** alias.
defineProps<Props>();

const form = useForm<CreateUserForm>({
    first_name: '',
    last_name: '',
    email: '',
    password: '',
    owner: false,
    photo: null,
});

// Submit function
const store = () => {
    form.post('/users');
};

// This component uses Layout as the default layout
defineOptions({
    layout: Layout,
});
</script>
