// ClientApp/src/Pages/Dashboard/Index.tsx
import MainLayout from '@/Layouts/MainLayout';
import { Link } from '@inertiajs/react';

function DashboardPage() {
    return (
        <div>
            <h1 className="mb-8 text-3xl font-bold">Dashboard</h1>
            <p className="mb-12 leading-normal">
                Hey there! Welcome to Ping CRM, a demo app designed to help
                illustrate how
                <a
                    className="mx-1 text-indigo-600 underline hover:text-orange-500"
                    href="https://inertiajs.com"
                >
                    Inertia.js
                </a>
                works with
                <a
                    className="ml-1 text-indigo-600 underline hover:text-orange-500"
                    href="https://reactjs.org/"
                >
                    React
                </a>
                .
            </p>
            <div>
                <Link className="btn-indigo mr-1" href="/500">
                    500 error
                </Link>
                <Link className="btn-indigo" href="/404">
                    404 error
                </Link>
            </div>
        </div>
    );
}

/**
 * Persistent Layout (Inertia.js)
 *
 * [Learn more](https://inertiajs.com/pages#persistent-layouts)
 */
DashboardPage.layout = (page: React.ReactNode) => (
    <MainLayout title="Dashboard" children={page} />
);

export default DashboardPage;

// ClientApp/src/Pages/Dashboard/Index.vue
<template>
    <div>
        <Head title="Dashboard" />
        <h1 class="mb-8 text-3xl font-bold">Dashboard</h1>
        <p class="mb-8 leading-normal">
            Hey there! Welcome to Ping CRM, a demo app designed to help
            illustrate how
            <a
                class="text-indigo-500 underline hover:text-orange-600"
                href="https://inertiajs.com"
                >Inertia.js</a
            >
            works.
        </p>
    </div>
</template>

<script setup lang="ts">
import Layout from '@/Shared/Layout.vue';
import type { InertiaSharedProps } from '@/Types/generated';
import { Head } from '@inertiajs/vue3';

defineProps<InertiaSharedProps>();

// This component uses Layout as the default layout
defineOptions({
    layout: Layout,
});
</script>
